server:
  port: 4004

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/payment_db

jwt:
  secret: ridelink-shared-secret-change-me-to-a-long-random-string
  expiration-ms: 3600000

fare:
  base: 100
  per-km-rate: 50

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
