server:
  port: 4002

spring:
  application:
    name: driver-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/account_db

jwt:
  secret: ridelink-shared-secret-change-me-to-a-long-random-string
  expiration-ms: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
